spin_manifest_version = "1"
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = ""
name = "view-counter"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "view-counter"
source = "target/view-counter.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]      # <-- Enable default KV storage
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
